# Generated by Django 4.2.17 on 2025-01-11 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepersonnel',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='course.course'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='personnel',
            field=models.ManyToManyField(related_name='personnel_courses', through='course.CoursePersonnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseassessmentcount',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_count', to='course.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='institutions',
            field=models.ManyToManyField(related_name='courses', to='institution.institution'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='instructor_courses', through='course.CourseInstructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('source', 'start_time', 'end_time'), name='unique_video_segment'),
        ),
        migrations.AddConstraint(
            model_name='sectioniteminfo',
            constraint=models.UniqueConstraint(fields=('section', 'sequence'), name='unique_section_sequence'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('module', 'sequence'), name='section_sequence_in_module'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'sequence'), name='module_sequence_in_course'),
        ),
        migrations.AddConstraint(
            model_name='coursepersonnel',
            constraint=models.UniqueConstraint(fields=('course', 'personnel'), name='unique_course_personnel'),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(fields=('course', 'instructor'), name='unique_course_instructor'),
        ),
        migrations.AddConstraint(
            model_name='courseinstance',
            constraint=models.UniqueConstraint(fields=('course', 'start_date', 'end_date'), name='unique_course_instance'),
        ),
    ]
