# Generated by Django 5.1.4 on 2025-01-07 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standaloneassessment',
            name='section',
            field=models.ForeignKey(help_text='The section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='course.section'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.standaloneassessment'),
        ),
        migrations.AddField(
            model_name='question',
            name='video_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.videoassessment'),
        ),
        migrations.AddConstraint(
            model_name='msqsolution',
            constraint=models.UniqueConstraint(fields=('question', 'choice'), name='unique_msq_choice'),
        ),
        migrations.AddConstraint(
            model_name='mcqsolution',
            constraint=models.UniqueConstraint(fields=('question', 'choice'), name='unique_mcq_choice'),
        ),
        migrations.AddConstraint(
            model_name='standaloneassessment',
            constraint=models.UniqueConstraint(fields=('section', 'sequence'), name='standaloneassessment_sequence_in_section'),
        ),
    ]
