# Generated by Django 4.2.17 on 2025-01-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='section',
            field=models.ForeignKey(help_text='The section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='course.section'),
        ),
        migrations.AddConstraint(
            model_name='msqsolution',
            constraint=models.UniqueConstraint(fields=('question', 'choice'), name='unique_msq_choice'),
        ),
        migrations.AddConstraint(
            model_name='mcqsolution',
            constraint=models.UniqueConstraint(fields=('question', 'choice'), name='unique_mcq_choice'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('section', 'sequence'), name='assessment_sequence_in_section'),
        ),
    ]
