<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-06 06:43
=======
# Generated by Django 5.1.4 on 2025-01-05 17:14
>>>>>>> 833a39aae9d63a4937a6431995c303e3c95b577a

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standaloneassessment',
            name='section',
            field=models.ForeignKey(help_text='The section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='course.section'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.standaloneassessment'),
=======
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.standaloneassessment'),
>>>>>>> 833a39aae9d63a4937a6431995c303e3c95b577a
        ),
        migrations.AddField(
            model_name='question',
            name='video_assessment',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.videoassessment'),
=======
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.videoassessment'),
>>>>>>> 833a39aae9d63a4937a6431995c303e3c95b577a
        ),
        migrations.AddConstraint(
            model_name='msqsolution',
            constraint=models.UniqueConstraint(fields=('question', 'choice'), name='unique_msq_choice'),
        ),
        migrations.AddConstraint(
            model_name='mcqsolution',
            constraint=models.UniqueConstraint(fields=('question', 'choice'), name='unique_mcq_choice'),
        ),
        migrations.AddConstraint(
            model_name='standaloneassessment',
            constraint=models.UniqueConstraint(fields=('section', 'sequence'), name='standaloneassessment_sequence_in_section'),
        ),
    ]
