# Generated by Django 5.1.4 on 2025-01-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.standaloneassessment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.videoassessment'),
        ),
    ]
